{% set name = "scikit-hep" %}
{% set version = "2023.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-hep-{{ version }}.tar.gz
  sha256: fb08b92c77c956d427f5afee17e6a3ae508db62886e5f37474550cc5063a4b49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - awkward ~=2.3.0
    - boost-histogram ~=1.3.0
    - decaylanguage ~=0.16.0
    - hepstats ~=0.7.0
    - hepunits ~=2.3.0
    - hist ~=2.7.0
    - histoprint ~=2.4.0
    - iminuit ~=2.22.0
    - matplotlib-base >3.4.0
    - mplhep ~=0.3.0
    - numpy >=1.13.1
    - particle ~=0.23.0
    - pylhe ~=0.7.0
    - python >=3.8
    - resample ~=1.6.0
    - uproot ~=5.0.0
    - vector ~=1.1.0

test:
  imports:
    - skhep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Metapackage of Scikit-HEP project tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
    - henryiii
