{% set name = "scikit-hep" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-hep-{{ version }}.tar.gz
  sha256: 637dd175e12f2a7743a013b9a3a1c02ba95c4a3ebb7e8fdbdc1ef743e028ebdf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - awkward ~=1.8.0
    - boost-histogram ~=1.3.0
    - decaylanguage ~=0.14.0
    - hepstats ~=0.5.0
    - hepunits ~=2.2.0
    - hist ~=2.6.0
    - histoprint ~=2.4.0
    - iminuit ~=2.16.0
    - matplotlib-base >2.0.0
    - mplhep ~=0.3.0
    - numpy >=1.13.1
    - particle ~=0.20.0
    - python >=3.7
    - resample~=1.5.0
    - uproot ~=4.2.0
    - vector ~=0.8.0

test:
  imports:
    - skhep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Metapackage of Scikit-HEP project tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
    - henryiii
