{% set name = "scikit-hep" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-hep-{{ version }}.tar.gz
  sha256: bf8b049adb3bad922b2c5546cfacd1b0ba9bc470b55082668e561400b8576c27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - awkward ~=1.1.0
    - awkward0 ~=0.15
    - boost-histogram ~=1.0.0
    - decaylanguage ~=0.10.0
    - hepstats ~=0.3.0
    - hepunits ~=2.1.0
    - hist ~=2.2.0
    - histoprint ~=2.0.0
    - iminuit ~=2.4.0
    - matplotlib-base >2.0.0
    - mplhep ~=0.2.0
    - numpy >=1.13.1
    - particle ~=0.14.0
    - python >=3.6
    - uproot ~=4.0.0
    - uproot3 ~=3.14.0
    - uproot3-methods ~=0.10.0

test:
  imports:
    - skhep
    - skhep.dataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Metapackage of Scikit-HEP project tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
