{% set name = "scikit-hep" %}
{% set version = "2024.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-hep-{{ version }}.tar.gz
  sha256: 82f8736f338e678f0d5b616a27dc9d53c8f28852d1fd39637c3cc031a16946e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - awkward ~=2.4.0
    - decaylanguage ~=0.16.0
    - hepstats ~=0.7.0
    - hepunits ~=2.3.0
    - hist ~=2.7.0
    - histoprint ~=2.4.0
    - iminuit ~=2.24.0
    - matplotlib-base >3.4.0
    - mplhep ~=0.3.0
    - numpy >=1.13.1
    - particle ~=0.23.0
    - pylhe ~=0.7.0
    - python >=3.8
    - resample ~=1.6.0
    - uproot ~=5.0.0
    - vector ~=1.1.0

test:
  imports:
    - skhep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Metapackage of Scikit-HEP project tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
    - henryiii
