{% set name = "scikit-hep" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-hep-{{ version }}.tar.gz
  sha256: b73a21b2466786944bb2085c204657fa416e10b00ea5bad6850e43e072f83f12

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - awkward ~=1.7.0
    - awkward0 ~=0.15
    - boost-histogram ~=1.2.0
    - decaylanguage ~=0.13.0
    - hepstats ~=0.5.0
    - hepunits ~=2.1.0
    - hist ~=2.5.0
    - histoprint ~=2.2.0
    - iminuit ~=2.8.0
    - matplotlib-base >2.0.0
    - mplhep ~=0.3.0
    - numpy >=1.13.1
    - particle ~=0.16.0
    - python >=3.7
    - uproot ~=4.1.0
    - uproot3 ~=3.14.0
    - uproot3-methods ~=0.10.0
    - vector ~=0.8.0

test:
  imports:
    - skhep
    - skhep.dataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Metapackage of Scikit-HEP project tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
    - henryiii
