{% set name = "scikit-hep" %}
{% set version = "4.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-hep-{{ version }}.tar.gz
  sha256: c7fd9989731ef4c624f1641c8dc1e0a76df8806cdde9d2097208186a78173c0a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - awkward ~=1.10.0
    - boost-histogram ~=1.3.0
    - decaylanguage ~=0.15.0
    - hepstats ~=0.6.0
    - hepunits ~=2.3.0
    - hist ~=2.6.0
    - histoprint ~=2.4.0
    - iminuit ~=2.17.0
    - matplotlib-base >2.0.0
    - mplhep ~=0.3.0
    - numpy >=1.13.1
    - particle ~=0.21.0
    - pylhe ~=0.4.0
    - python >=3.7
    - resample ~=1.5.0
    - uproot ~=4.3.0
    - vector ~=0.10.0

test:
  imports:
    - skhep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Metapackage of Scikit-HEP project tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
    - henryiii
